swagger: "2.0"
info: 
  description: Swagger doc for /api/sys/mb/chassis_eeprom  
  title: Swagger doc for /api/sys/mb/chassis_eeprom  
  version: 1.0.0
paths: 
  /api/sys/mb/chassis_eeprom: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              Product Production State: 
                type: string
              Location on Fabric: 
                type: string
              ODM PCBA Part Number: 
                type: string
              PCB Manufacturer: 
                type: string
              Product Version: 
                type: string
              Product Asset Tag: 
                type: string
              Local MAC: 
                type: string
              Facebook PCB Part Number: 
                type: string
              Version: 
                type: string
              CRC8: 
                type: string
              Assembled At: 
                type: string
              Extended MAC Base: 
                type: string
              System Manufacturer: 
                type: string
              ODM PCBA Serial Number: 
                type: string
              Facebook PCBA Part Number: 
                type: string
              System Manufacturing Date: 
                type: string
              Product Serial Number: 
                type: string
              Product Sub-Version: 
                type: string
              Product Part Number: 
                type: string
              Wedge EEPROM /sys/class/i2c-dev/i2c-28/device/28-0050/eeprom: 
                type: string
              Extended MAC Address Size: 
                type: string
              System Assembly Part Number: 
                type: string
              Product Name: 
                type: string
            