swagger: "2.0"
info: 
  description: Swagger doc for /api/sys/mb  
  title: Swagger doc for /api/sys/mb  
  version: 1.0.0
paths: 
  /api/sys/mb: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              Resources: 
                type: array
                items: 
                  type: string
              Actions: 
                type: array
                items: 
                  type: string
              Information: 
                type: object
                additionalProperties: false
                properties: 
                  Description: 
                    type: string
            