swagger: "2.0"
info: 
  description: Swagger doc for /api/iom/logs  
  title: Swagger doc for /api/iom/logs  
  version: 1.0.0
paths: 
  /api/iom/logs: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              Information: 
                type: object
                additionalProperties: false
                properties: 
                  Logs: 
                    type: array
                    items: 
                      type: string
              Resources: 
                type: array
                items: 
                  type: string
              Actions: 
                type: array
                items: 
                  type: string
            