swagger: "2.0"
info: 
  description: Swagger doc for /api/sys/firmware_info/scm  
  title: Swagger doc for /api/sys/firmware_info/scm  
  version: 1.0.0
paths: 
  /api/sys/firmware_info/scm: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              Information: 
                type: object
                additionalProperties: false
                properties: 
                  P1V05 VR Version: 
                    type: string
                  ME Version: 
                    type: string
                  Bridge-IC Version: 
                    type: string
                  Bridge-IC Bootloader Version: 
                    type: string
                  PVCCIN VR Version: 
                    type: string
                  CPLD Version: 
                    type: string
                  BIOS Version: 
                    type: string
                  DDRAB VR Version: 
                    type: string
              Actions: 
                type: array
                items: 
                  type: string
              Resources: 
                type: array
                items: 
                  type: string
            