swagger: "2.0"
info: 
  description: Swagger doc for /api/sled/mb/sensors  
  title: Swagger doc for /api/sled/mb/sensors  
  version: 1.0.0
paths: 
  /api/sled/mb/sensors: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              Information: 
                type: object
                additionalProperties: false
                properties: 
                  MB_VR_CPU0_VCCIN_POWER: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU0_VCCIO_POWER: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU1_VDDQ_GRPC_CURR: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU1_VCCIO_POWER: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_OUTLET_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU1_VDDQ_GRPC_POWER: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_CONN_P12V_INA230_CURR: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU0_VSA_POWER: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_CPU1_DIMM_GRPD_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU1_VCCIO_CURR: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_PCH_P1V05_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_CONN_P12V_INA230_VOL: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU0_VCCIN_CURR: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU1_VSA_POWER: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_PCH_P1V05_CURR: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU1_VCCIN_POWER: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU0_VSA_VOLT: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_P3V_BAT: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_P5V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU1_VDDQ_GRPC_VOLT: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU1_VCCIN_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU0_VCCIO_VOLT: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU1_VCCIO_VOLT: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_HSC_IN_POWER: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU0_VDDQ_GRPB_CURR: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_HSC_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU0_VCCIO_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_CPU0_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_CPU0_DIMM_GRPB_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_P3V3_STBY: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU0_VCCIN_VOLT: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_PCH_PVNN_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU0_VCCIO_CURR: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_CPU1_DIMM_GRPC_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU0_VCCIN_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_CPU1_TJMAX: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU0_VDDQ_GRPA_CURR: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU0_VSA_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU0_VDDQ_GRPA_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU1_VSA_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_PCH_PVNN_VOLT: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU0_VDDQ_GRPA_VOLT: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU0_VSA_CURR: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_PVNN_PCH_STBY: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_PCH_PVNN_POWER: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU0_VDDQ_GRPA_POWER: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_INLET_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_FAN1_TACH: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_CPU0_PKG_POWER: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_PCH_P1V05_POWER: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_HSC_IN_VOLT: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU0_VDDQ_GRPB_VOLT: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_PCH_P1V05_VOLT: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU1_VCCIO_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_P5V_STBY: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_CONN_P12V_INA230_PWR: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_P12V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_OUTLET_REMOTE_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU1_VDDQ_GRPC_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU1_VDDQ_GRPD_POWER: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_CPU0_THERM_MARGIN: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU1_VDDQ_GRPD_VOLT: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_P1V05: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU0_VDDQ_GRPB_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_P3V3: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU1_VDDQ_GRPD_CURR: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_CPU0_DIMM_GRPA_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU1_VCCIN_CURR: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_CPU1_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_PCH_PVNN_CURR: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU0_VDDQ_GRPB_POWER: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_INLET_REMOTE_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_FAN0_TACH: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_PCH_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU1_VCCIN_VOLT: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU1_VDDQ_GRPD_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_CPU0_TJMAX: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_CPU1_THERM_MARGIN: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU1_VSA_VOLT: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_HSC_OUT_CURR: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_CPU1_PKG_POWER: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU1_VSA_CURR: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
              Resources: 
                type: array
                items: 
                  type: string
              Actions: 
                type: array
                items: 
                  type: string
            