swagger: "2.0"
info: 
  description: Swagger doc for /api/sensors  
  title: Swagger doc for /api/sensors  
  version: 1.0.0
paths: 
  /api/sensors: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              Information: 
                type: object
                additionalProperties: false
                properties: 
                  INA230 Power: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  SP_FAN1_PWM: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SP_SENSOR_P2V5_BMC_STBY: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  INA230 Voltage: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  MB Outlet Temp_T: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  SP_HSC_PEAK_PIN: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB Inlet Temp: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  PV_BAT: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  PVDDCR_SOC VR P: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  PVPP_ABCD: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  P3V3_MB: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  SYSTEM_AIRFLOW: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PVDDCR_SOC VR T: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  SP_HSC_PEAK_IOUT: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB Outlet Temp_B: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  SP_P12V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SP_FAN1_TACH: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SP_SENSOR_P1V15_BMC_STBY: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SOC DIMMD Temp: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  SP_HSC_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SOC DIMMG Temp: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  PVDDCR_SOC VR I: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  SOC DIMMH Temp: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  PVDDIO_ABCD VR I: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  SOC Package Pwr: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  SP_P3V3: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SP_P5V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SP_P3V3_STBY: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PVDDCR_SOC VR V: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  SP_P12V_SLOT4: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SOC DIMMC Temp: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  NVMe1 CTemp: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  SP_P12V_SLOT1: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PVDDIO_EFGH VR T: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  SP_P12V_SLOT3: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SP_P12V_SLOT2: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PVDDIO_ABCD_VR V: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  PVDDIO_ABCD VR T: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  PVDDCR_CPU VR I: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  PVPP_EFGH: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  PVDDCR_CPU VR V: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  SP_INLET_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PVDDCR_CPU VR T: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  PVDDIO_ABCD VR P: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  SP_SENSOR_P1V2_BMC_STBY: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  PVDDCR_CPU VR P: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  SP_OUTLET_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  HOST_BOOT_TEMP: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  SP_HSC_IN_POWER: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SP_HSC_IN_VOLT: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  P12V_STBY_MB: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  SP_FAN0_TACH: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SOC CPU0 Temp: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  PVDDIO_EFGH VR I: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  MEZZ_SENSOR_TEMP: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SP_P1V8_STBY: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  P1V8_BIC: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  PVDDIO_EFGH VR P: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  P1V8_STBY_BIC: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  PVDDIO_EFGH_VR V: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  SP_HSC_OUT_CURR: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  SP_FAN0_PWM: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  INA260 Voltage: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  P3V3_STBY_MB: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
                  INA260 Power: 
                    type: array
                    items: 
                      type: object
                      additionalProperties: false
                      properties: 
                        value: 
                          type: string
              Resources: 
                type: array
                items: 
                  type: string
              Actions: 
                type: array
                items: 
                  type: string
            